function clearMemory
C={'Ab';'Ab_TE';'Ab_TM';'Fr';'K';'Kb';'M';'MA';'MB';'MG';...
    'Mt';'R';'R_TE';'R_TM';'R_Td';'Sg';'Step';'T';'T_T';'T_TE';...
    'T_TM';'T_Td';'Td';'Tr';'c';'e';'epsilonAg_r';'fname';'fun';...
    'fval';'g_ei';'g_er';'j';'muA';'muB';'muD';'omegaAg_p';'p';'tauAg'};
clear(C{:});
end
