function [Loss]= fitfunc(Ab_TM,T_TM,lambda_margin,lambda_center)
FWHM=125e-9;
sigma=FWHM/2/sqrt(2*log(2));
eta=0.9;
ind_center=(lambda_margin>lambda_center-FWHM/2 & lambda_margin<lambda_center+FWHM/2);
ind=find(ind_center~=0);
N=size(ind,2);
% lambda_center=1310e-9;
Loss=1/N*sqrt(...
                 sum(abs(...
                   Ab_TM(ind)-eta*...
                    exp(-0.5*(...
                                (lambda_margin(ind)-lambda_center)./sigma).^2)...
                                                                            ).^2))+...
       sqrt(sum(...
                    abs(T_TM(ind)).^2));

end