function [Loss]= Newfitfunc(TM,lambda_center,FWHM,eta)
% FWHM=80e-9;
sigma=FWHM/2/sqrt(2*log(2));
% eta=0.5;
lambda_margin=TM.Lambda;
N=size(lambda_margin,2);
% lambda_center=1310e-9;
Loss=1/N*sqrt(...
                 sum(abs(...
                   TM.Ab-eta*...
                    exp(-0.5*(...
                               (lambda_margin-lambda_center)./sigma).^2)...
                                                                            ).^2))+...
       sqrt(sum(...
                    abs(TM.T).^2));
end